import os
import numpy as np
import pandas as pd
from skimage.metrics import structural_similarity as ssim
from io_utils import load_frames

def compute_nrmse(gt, test):
    """
    Computes the Normalized Root Mean Squared Error.
    Normalized by the dynamic range of the ground truth image.
    """
    rmse = np.sqrt(np.mean((gt - test) ** 2))
    denom = gt.max() - gt.min()
    if denom == 0:
        return rmse
    return rmse / denom

def main():
    # 1. Load the three sets of frames
    # Assuming your folder names match the ones generated by main.py
    try:
        u_true, names = load_frames("data", max_frames=30)
        u_dirty, _    = load_frames("dirty_reconstruction", max_frames=30)
        u_rec, _      = load_frames("reconstruction", max_frames=30)
    except FileNotFoundError as e:
        print(f"Error loading frames: {e}")
        print("Please ensure 'data', 'dirty_reconstruction', and 'reconstruction' directories exist.")
        return

    K = len(names)
    metrics = []

    print(f"Evaluating {K} frames...\n")

    # 2. Loop through frames and compute metrics
    for k in range(K):
        gt = u_true[k]
        dirty = u_dirty[k]
        rec = u_rec[k]

        # Inside evaluate.py right before computing SSIM/NRMSE:
        # Normalize test images to the exact 0.0 - 1.0 dynamic range of the ground truth
        rec = (rec - rec.min()) / (rec.max() - rec.min() + 1e-8)
        dirty = (dirty - dirty.min()) / (dirty.max() - dirty.min() + 1e-8)
        # Compute Dirty Metrics
        nrmse_dirty = compute_nrmse(gt, dirty)
        ssim_dirty = ssim(gt, dirty, data_range=gt.max() - gt.min())

        # Compute Reconstruction Metrics
        nrmse_rec = compute_nrmse(gt, rec)
        ssim_rec = ssim(gt, rec, data_range=gt.max() - gt.min())

        metrics.append({
            "Frame": names[k],
            "Dirty_NRMSE": nrmse_dirty,
            "Dirty_SSIM": ssim_dirty,
            "Rec_NRMSE": nrmse_rec,
            "Rec_SSIM": ssim_rec
        })

    # 3. Convert to DataFrame for clean formatting and aggregation
    df = pd.DataFrame(metrics)

    # 4. Print Summary Statistics
    print("=" * 65)
    print(f"{'METRIC SUMMARY':^65}")
    print("=" * 65)
    print(f"Average Dirty NRMSE:        {df['Dirty_NRMSE'].mean():.4f}")
    print(f"Average Reconstructed NRMSE: {df['Rec_NRMSE'].mean():.4f}  (Lower is better)")
    print("-" * 65)
    print(f"Average Dirty SSIM:         {df['Dirty_SSIM'].mean():.4f}")
    print(f"Average Reconstructed SSIM:  {df['Rec_SSIM'].mean():.4f}  (Higher is better)")
    print("=" * 65)

    # Optional: Save detailed frame-by-frame report to CSV
    df.to_csv("reconstruction_report.csv", index=False)
    print("\nDetailed breakdown saved to 'reconstruction_report.csv'")

if __name__ == "__main__":
    main()